using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Detection : MonoBehaviour
{
    [Header(" Managers ")]
    [SerializeField] private Formation squadFormation;
    [SerializeField] private Runner runner;

    [Header(" Settings ")]
    [SerializeField] private LayerMask doorLayer;

    void Start()
    {

    }


    void Update()
    {
        DetectDoors();
    }

    private void DetectDoors()
    {
        Collider[] detectedDoors = Physics.OverlapSphere(transform.position, squadFormation.GetSquadRadius(), doorLayer);

        if (detectedDoors.Length <= 0) return;

        Collider collidedDoorCollider = detectedDoors[0];
        Door collidedDoor = collidedDoorCollider.GetComponentInParent<Door>();

        int runnersAmountToAdd = collidedDoor.GetRunnersAmountToAdd(collidedDoorCollider, transform.childCount);
        squadFormation.AddRunners(runnersAmountToAdd);
    }
}


   